### ISSUE TITLE
errors when editing new user V.9

### ISSUE THREAD

**Issue by lisandi** [it-projects-llc/access-addons#27]
Hi Yelizariev, 

we receive the following error message when we try to edit a user.
The error is coming form the module 

https://webcache.googleusercontent.com/search?q=cache:fihghjQybusJ:https://github.com/yelizariev/access-addons/issues/15+&cd=1&hl=en&ct=clnk&gl=th&lr=lang_de|lang_en|lang_es|lang_fr|lang_th

We are on latest Odoo version and are also using latest versions of your module.

```
Invalid view definition

Error details:
Field `sel_groups_11` does not exist

Error context:
View `res.users.groups`
[view_id: 152, xml_id: base.user_groups_view, model: res.users, parent_id: 149]
```

Thanks Andi

Recreate:
Version 9 newest version from git
Modules newest Versions from git

login as User with access to modify the Users
Settings
Users - Users
Click on User
Edit
>>> Error Message appears

Message disappears when deinstalling access_restricted which also deinstalls other modules!
access_apps : to remove
access_restricted : to remove
access_settings_menu : to remove
web_debranding : to remove
website_debranding : to remove

**Comment by yelizariev** [comment]
Thank you for report!
I have fixed and added automated tests. Try latest version
