### ISSUE TITLE
Cannot add users to Sales team (Access Rights)

### ISSUE THREAD

**Issue by kurkop** [it-projects-llc/access-addons#36]
Hi, 
Users cannot be added to sales teams when install hidden_admin.

Steps:

- Install hidden_admin
- Install Sales
- Create a user with crm permissions
- Install CRM
- Go to Sales->Team of sales
- Try add users to "direct sales".

I try uninstall hidden_access and install (It works)
Too "disable" the rule "Only admin can see admin user" (Active field) and this works. If I active before too works.

Note: This test are execute without superuser, in other words, other user.

**Comment by yelizariev** [comment]
Could you send screenshots of the error you got. Which odoo version do you use?

**Comment by kurkop** [comment]
@yelizariev  I use Odoo 9.0. Screenshot (when I want save):

![screenshot-www felicity com co 2016-08-02 08-26-12](https://cloud.githubusercontent.com/assets/2367831/17330073/fee8850e-588a-11e6-9338-af802b3b849a.png)

Disabling rule:
![screenshot-localhost 2016-08-02 08-32-04](https://cloud.githubusercontent.com/assets/2367831/17330247/b45adc52-588b-11e6-8416-9bb68e0cd0fd.png)

In this moment I can save. If I active rule again, I can save too.

This bug is corrected in two cases:

1. Uninstall and install hidden_admin.
2. Disable and active "Only admin can see admin user" rule.

**Comment by yelizariev** [comment]
I suggest you uninstall the module, remove Administrator from sales team, install the module and then you will be able to add users. You shall not use Administrator as a usual user and add it sales_team, for example

**Comment by yelizariev** [comment]
I can only add a not to README: https://github.com/it-projects-llc/access-addons/blob/9.0/hidden_admin/README.rst#known-issues

Thank you for report

**Comment by kurkop** [comment]
Excuse me, but this fails again. If I install CRM and disable the admin rights (and add as portal user) and install hidden_admin. Create a new user with sales manager permission and login show this error:

```
Sorry, you are not allowed to modify this document. Only users with the following access level are currently allowed to do that:
- Administration/Access Rights

(Document model: res.users) 
```

**Comment by yelizariev** [comment]
I'll check it later

**Comment by yelizariev** [comment]
@kurkop try to remove Admin from Team Members of Sales Manager
